<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Str;
use Carbon\Carbon;

class ProducersSeeder extends Seeder
{
    public function run()
    {
        $producers = [
            [
                'name' => 'Juan',
                'lastname' => 'García',
                'description' => 'Productor de madera de pino con 20 años de experiencia en el sector forestal.',
                'is_active' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'María',
                'lastname' => 'Rodríguez',
                'description' => 'Especialista en gestión sostenible de bosques nativos.',
                'is_active' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Carlos',
                'lastname' => 'López',
                'description' => 'Productor de eucalipto para industria papelera.',
                'is_active' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Ana',
                'lastname' => 'Martínez',
                'description' => 'Gestora de plantaciones forestales certificadas FSC.',
                'is_active' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Pedro',
                'lastname' => 'Sánchez',
                'description' => 'Productor de madera noble para mueblería fina.',
                'is_active' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Laura',
                'lastname' => 'Fernández',
                'description' => 'Especialista en reforestación y conservación de suelos.',
                'is_active' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Diego',
                'lastname' => 'Pérez',
                'description' => 'Productor de madera para construcción y estructuras.',
                'is_active' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Elena',
                'lastname' => 'Gómez',
                'description' => 'Gestora de bosques comunitarios y proyectos sociales.',
                'is_active' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Miguel',
                'lastname' => 'Hernández',
                'description' => 'Productor de madera certificada para exportación.',
                'is_active' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Sofía',
                'lastname' => 'Díaz',
                'description' => 'Ingeniera forestal especializada en silvicultura preventiva.',
                'is_active' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Javier',
                'lastname' => 'Ruiz',
                'description' => 'Productor de leña y biomasa para energía renovable.',
                'is_active' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Carmen',
                'lastname' => 'Moreno',
                'description' => 'Gestora de viveros forestales y producción de plantines.',
                'is_active' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Antonio',
                'lastname' => 'Álvarez',
                'description' => 'Productor tradicional con técnicas ancestrales de manejo forestal.',
                'is_active' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Isabel',
                'lastname' => 'Romero',
                'description' => 'Especialista en dendrología y especies nativas.',
                'is_active' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Francisco',
                'lastname' => 'Navarro',
                'description' => 'Productor de corcho y productos forestales no maderables.',
                'is_active' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
        [
                'name' => 'Fernando',
                'lastname' => 'Ramírez',
                'description' => 'Productor de caucho natural con 15 años en el cultivo de heveas.',
                'is_active' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Lucía',
                'lastname' => 'Vargas',
                'description' => 'Especialista en producción de aguacate hass para exportación.',
                'is_active' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Roberto',
                'lastname' => 'Silva',
                'description' => 'Productor de café arábigo en zonas de alta montaña.',
                'is_active' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Patricia',
                'lastname' => 'Cortés',
                'description' => 'Productora de cacao fino de aroma con certificación orgánica.',
                'is_active' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Andrés',
                'lastname' => 'Ortega',
                'description' => 'Productor de caña de azúcar para panela y derivados.',
                'is_active' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Gabriela',
                'lastname' => 'Reyes',
                'description' => 'Productora de flores tropicales para mercado internacional.',
                'is_active' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Héctor',
                'lastname' => 'Mendoza',
                'description' => 'Productor de banano orgánico para mercados europeos.',
                'is_active' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Silvia',
                'lastname' => 'Guerrero',
                'description' => 'Productora de arroz de secano con técnicas tradicionales.',
                'is_active' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Óscar',
                'lastname' => 'Rojas',
                'description' => 'Productor de palma africana para aceite vegetal.',
                'is_active' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Teresa',
                'lastname' => 'Castillo',
                'description' => 'Productora de quinua real en el altiplano andino.',
                'is_active' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Daniel',
                'lastname' => 'Herrera',
                'description' => 'Productor de maíz amarillo duro para industria avícola.',
                'is_active' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Marta',
                'lastname' => 'Delgado',
                'description' => 'Productora de espárragos verdes para exportación.',
                'is_active' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Pablo',
                'lastname' => 'Cruz',
                'description' => 'Productor de uvas para vino en viñedos de altura.',
                'is_active' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Eva',
                'lastname' => 'Medina',
                'description' => 'Productora de berries (frambuesas y arándanos).',
                'is_active' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Raúl',
                'lastname' => 'Vega',
                'description' => 'Productor de soya transgénica para industria alimentaria.',
                'is_active' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Julia',
                'lastname' => 'Campos',
                'description' => 'Productora de hierbas aromáticas para uso medicinal.',
                'is_active' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Enrique',
                'lastname' => 'Santos',
                'description' => 'Productor de trigo para harina panificadora.',
                'is_active' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Raquel',
                'lastname' => 'Peña',
                'description' => 'Productora de ajo chileno para mercado nacional.',
                'is_active' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Guillermo',
                'lastname' => 'Aguilar',
                'description' => 'Productor de algodón Pima de fibra extra larga.',
                'is_active' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Cristina',
                'lastname' => 'Suárez',
                'description' => 'Productora de papa nativa con variedades ancestrales.',
                'is_active' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],       
            [
                'name' => 'Alberto',
                'lastname' => 'Méndez',
                'description' => 'Productor de mango Kent para exportación a Europa.',
                'is_active' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Alicia',
                'lastname' => 'Rivera',
                'description' => 'Productora de cebolla roja en zonas costeras.',
                'is_active' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Felipe',
                'lastname' => 'Miranda',
                'description' => 'Productor de piña golden extra dulce.',
                'is_active' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Inés',
                'lastname' => 'Valdez',
                'description' => 'Productora de limón sutil para industria de jugos.',
                'is_active' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Mario',
                'lastname' => 'Cárdenas',
                'description' => 'Productor de frijol negro para consumo nacional.',
                'is_active' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Olga',
                'lastname' => 'Parra',
                'description' => 'Productora de zanahoria baby para ensaladas.',
                'is_active' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Santiago',
                'lastname' => 'Escobar',
                'description' => 'Productor de tomate cherry hidropónico.',
                'is_active' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Marina',
                'lastname' => 'Castro',
                'description' => 'Productora de alcachofas para conservas.',
                'is_active' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Víctor',
                'lastname' => 'Flores',
                'description' => 'Productor de papa amarilla para industria de snacks.',
                'is_active' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Natalia',
                'lastname' => 'Morales',
                'description' => 'Productora de chía orgánica para superfoods.',
                'is_active' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Ricardo',
                'lastname' => 'Ramos',
                'description' => 'Productor de camote naranja para procesamiento.',
                'is_active' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Beatriz',
                'lastname' => 'Castillo',
                'description' => 'Productora de maracuyá para concentrados.',
                'is_active' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Jorge',
                'lastname' => 'Herrera',
                'description' => 'Productor de yuca para almidón y harina.',
                'is_active' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Claudia',
                'lastname' => 'Guerrero',
                'description' => 'Productora de palta hass para exportación.',
                'is_active' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Luis',
                'lastname' => 'Vargas',
                'description' => 'Productor de sandía sin semillas.',
                'is_active' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Adriana',
                'lastname' => 'Ortega',
                'description' => 'Productora de melón cantaloupe.',
                'is_active' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Fernando',
                'lastname' => 'Silva',
                'description' => 'Productor de espinaca para congelados.',
                'is_active' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Verónica',
                'lastname' => 'Reyes',
                'description' => 'Productora de brócoli para industria alimentaria.',
                'is_active' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Manuel',
                'lastname' => 'Mendoza',
                'description' => 'Productor de avena forrajera para ganado.',
                'is_active' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Lucía',
                'lastname' => 'Cortés',
                'description' => 'Productora de coliflor orgánica.',
                'is_active' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ]
        ];

        DB::table('producers')->insert($producers);
    }
}